//general
#define ROTATION 3
#define DISPLAY_BRIGHTNESS 0.7
#define LOADING_SCREEN_TIME 1

//settings
#define DEBUG false

#define STAGE_TIME 1*800
#define VENTILATING_TIMEOUT 5*1000

#define AVERAGING_MEASUREMENTS 100
#define AVERAGING_GRADIENT 10
#define ALPHA_MEASUREMENTS 0.7
#define ALPHA_LOWEST 0.5

#define MAX_INCREASE 1.5
#define MAX_DECREASE 0.9
#define MAX_INCREASE_LOWEST 50

#define TOUCH_RESISTANCE 10000000

#define MINPRESSURE -1
#define MAXPRESSURE 0

#define TS_MINX -2300
#define TS_MINY -2400
#define TS_MAXX 740
#define TS_MAXY 540

#define TOUCH_INACCURACY 5
#define TOUCH_INACCURACY_X TOUCH_INACCURACY
#define TOUCH_INACCURACY_Y TOUCH_INACCURACY

#define DD_MARGIN 2

#define TOUCH_CALIBRATION_BOX_MARGIN 5
#define TOUCH_CALIBRATION_BOX_SIZE 10
#define TOUCH_CALIBRATION_BOX_COLOR RED
#define TOUCH_CALIBRATION_BOX_CALIBRATION_COLOR BLUE
#define TOUCH_CALIBRATION_BOX_CHANGE (TOUCH_CALIBRATION_BOX_SIZE + TOUCH_CALIBRATION_BOX_MARGIN)
#define TOUCH_CALIBRATION_BOX_CHANGE_X (DISPLAY_LENGTH - TOUCH_CALIBRATION_BOX_CHANGE)
#define TOUCH_CALIBRATION_BOX_CHANGE_Y (DISPLAY_HEIGHT - TOUCH_CALIBRATION_BOX_CHANGE)
#define TOUCH_CALIBRATION_HEADER_SIZE SIZE(DISPLAY_LENGTH, round(DISPLAY_HEIGHT*0.3), 11)
#define TOUCH_CALIBRATION_TEXT_SIZE SIZE(DISPLAY_LENGTH, round(DISPLAY_HEIGHT*0.2), 14)

#define MENU_ICON_START_X (MENU_ICON_END_X - MENU_ICON_LENGTH)
#define MENU_ICON_START_Y MENU_ICON_MARGIN
#define MENU_ICON_END_X (DISPLAY_LENGTH - MENU_ICON_MARGIN)
#define MENU_ICON_END_Y (MENU_ICON_START_Y + MENU_ICON_HEIGHT)
#define MENU_ICON_MARGIN 5
#define MENU_ICON_HEIGHT 32
#define MENU_ICON_LENGTH 32
#define MENU_TITLE_SIZE SIZE(STATUS_LENGTH, STATUS_HEIGHT, 4)

#define MENU_HEIGHT (DISPLAY_HEIGHT - GRAPH_END_Y)
#define MENU_SECTION_HEIGHT floor(MENU_HEIGHT/3)
#define MENU_MARGIN_LEFT (DISPLAY_MARGIN_LEFT*2)
#define MENU_MARGIN_RIGHT DISPLAY_MARGIN_RIGHT*2
#define MENU_SECTION_SIZE SIZE((DISPLAY_LENGTH*0.6), MENU_SECTION_HEIGHT, 8)
#define MENU_SLIDER_RADIUS round(MENU_SLIDER_HEIGHT/2)
#define MENU_SLIDER_LENGTH (MENU_SLIDER_HEIGHT*2)
#define MENU_SLIDER_HEIGHT round(MENU_SECTION_HEIGHT/2)
#define MENU_SLIDER_MARGIN_VERTIAL round((MENU_SECTION_HEIGHT - MENU_SLIDER_HEIGHT)/2)
#define MENU_SLIDER_START_X (MENU_SLIDER_END_X - MENU_SLIDER_LENGTH)
#define MENU_SLIDER_END_X (DISPLAY_LENGTH - MENU_MARGIN_RIGHT)
#define MENU_SLIDER1_START_Y (GRAPH_END_Y + MENU_SLIDER_MARGIN_VERTIAL)
#define MENU_SLIDER1_END_Y (GRAPH_END_Y + MENU_SECTION_HEIGHT)
#define MENU_SLIDER_DOT_RADIUS round(MENU_SECTION_HEIGHT/3)
#define MENU_SLIDER_DOT_HEIGHT round(MENU_SECTION_HEIGHT/2)
#define MENU_SLIDER_DOT_START_X (MENU_SLIDER_START_X + MENU_SLIDER_RADIUS)
#define MENU_SLIDER_DOT_END_X (MENU_SLIDER_END_X - MENU_SLIDER_RADIUS)

//DisplayV1
#define AVERAGING_GRAPH 1
#define ALPHA_GRAPH 0.7

//DisplayV2

//settings
#define COLOR_MODE true
#define COLORED_BAR true
#define COLORED_STATE true
#define COLORED_TIME true
#define COLORED_PPM true
#define COLORED_CHART true


#define DISPLAYED_PPM_LOWEST  400
#define DISPLAYED_PPM_HIGHEST 1000

//display
#define DISPLAY_LENGTH             320
#define DISPLAY_HEIGHT             240
#define DISPLAY_MARGIN             0
#define DISPLAY_MARGIN_HORIZONTAL  (DISPLAY_MARGIN + round(DISPLAY_LENGTH * 0.025))
#define DISPLAY_MARGIN_VERTICAL    (DISPLAY_MARGIN + round(DISPLAY_HEIGHT * 0.033))
#define DISPLAY_MARGIN_LEFT        DISPLAY_MARGIN_HORIZONTAL
#define DISPLAY_MARGIN_RIGHT       DISPLAY_MARGIN_HORIZONTAL
#define DISPLAY_MARGIN_TOP         DISPLAY_MARGIN_VERTICAL
#define DISPLAY_MARGIN_BOTTOM      DISPLAY_MARGIN_VERTICAL
//font
#define LETTER_LENGTH              6
#define LETTER_HEIGHT              8
//Status Info
#define STATUS_LENGTH              round(DISPLAY_LENGTH * 0.8)
#define STATUS_HEIGHT              round(DISPLAY_HEIGHT * 0.13)
#define STATUS_MARGIN_TOP          DISPLAY_MARGIN_TOP
#define STATUS_MARGIN_BOTTOM       DISPLAY_MARGIN_BOTTOM
#define STATUS_SIZE                SIZE(STATUS_LENGTH, STATUS_HEIGHT, state.getTitle().length())
#define LAST_STATUS_SIZE           SIZE(STATUS_LENGTH, STATUS_HEIGHT, lastState.getTitle().length())
//PPM
#define PPM_MARGIN_LEFT            DISPLAY_MARGIN_LEFT
#define PPM_MARGIN_BOTTOM          DISPLAY_MARGIN_BOTTOM
#define PPM_MARGIN_RIGHT           DISPLAY_MARGIN_RIGHT
#define PPM_LENGTH                 round(DISPLAY_LENGTH * 0.5)
#define PPM_HEIGHT                 round(DISPLAY_HEIGHT * 0.2)
#define PPM_Y                      round(DISPLAY_HEIGHT - (DATABOX_HEIGHT - PPM_SIZE*(LETTER_HEIGHT + 1))/2)
#define PPM_SIZE                   SIZE(0, PPM_HEIGHT, 0)
#define PPM_STRING_X               (PPM_MARGIN_LEFT + (3*LETTER_LENGTH - 1)*PPM_SIZE + PPM_MARGIN_RIGHT)
#define PPM_STRING_Y               (PPM_Y - PPM_MARGIN_BOTTOM)
#define PPM_STRING_SIZE            SIZE((PPM_LENGTH - PPM_STRING_X), 0, 3)
//Timer
#define TIMER_MARGIN_RIGHT         DISPLAY_MARGIN_RIGHT
#define TIMER_MARGIN_BOTTOM        DISPLAY_MARGIN_BOTTOM
#define TIMER_LENGTH               round(DISPLAY_LENGTH * 0.4)
#define TIMER_HEIGHT               round(DISPLAY_HEIGHT * 0.2)
#define TIMER_X                    (DISPLAY_LENGTH - TIMER_MARGIN_RIGHT)
#define TIMER_Y                    round(DISPLAY_HEIGHT - (DATABOX_HEIGHT - TIMER_SIZE*(LETTER_HEIGHT + 1))/2)
#define TIMER_SIZE                 SIZE(TIMER_LENGTH, TIMER_HEIGHT, 5)
//Databox
#define DATABOX_HEIGHT             (round(DISPLAY_HEIGHT * 0.3) - DATABOX_BAR_THICKNESS)
#define DATABOX_Y                  (DISPLAY_HEIGHT - DATABOX_HEIGHT)
#define DATABOX_BAR_Y              (DATABOX_Y - DATABOX_BAR_THICKNESS)
#define DATABOX_BAR_THICKNESS      round(DISPLAY_HEIGHT * 0.033)
#define DATABOX_MARGIN_TOP         DISPLAY_MARGIN_TOP

//V2
//Bar
#define BAR_BORDER_LENGTH          round(DISPLAY_LENGTH * 0.8)
#define BAR_BORDER_HEIGHT          round(DISPLAY_HEIGHT * 0.4)
#define BAR_MARGIN_LEFT            round(DISPLAY_LENGTH * 0.1)
#define BAR_MARGIN_RIGHT           round(DISPLAY_LENGTH * 0.1)
#define BAR_MARGIN_TOP             DISPLAY_MARGIN_TOP
#define BAR_MARGIN_BOTTOM          DISPLAY_MARGIN_BOTTOM
#define BAR_BORDER_X               BAR_MARGIN_LEFT
#define BAR_BORDER_Y               (STATUS_MARGIN_TOP + STATUS_HEIGHT + STATUS_MARGIN_BOTTOM + BAR_MARGIN_TOP)
#define BAR_BORDER_THICKNESS       round(DISPLAY_LENGTH * 0.01)
#define BAR_HEIGHT                 (BAR_BORDER_HEIGHT - 2*BAR_BORDER_THICKNESS)
#define BAR_LENGTH                 (BAR_BORDER_LENGTH - 2*BAR_BORDER_THICKNESS)
#define BAR_START_X                (BAR_BORDER_X + BAR_BORDER_THICKNESS)
#define BAR_Y                      (BAR_BORDER_Y + BAR_BORDER_THICKNESS)
#define BAR_END_X                  (BAR_LENGTH + BAR_START_X)
#define FIRST_SECTION_X            map(LIMIT_GOOD, DISPLAYED_PPM_LOWEST, DISPLAYED_PPM_HIGHEST, BAR_START_X, BAR_END_X)
#define SECOND_SECTION_X           map(LIMIT_MEDIUM, DISPLAYED_PPM_LOWEST, DISPLAYED_PPM_HIGHEST, BAR_START_X, BAR_END_X)
#define BAR_SECTIONS_LENGTH        round(DISPLAY_LENGTH * 0.02)
#define BAR_SECTIONS_HEIGHT        (BAR_SECTIONS_Y_MARGIN*2 + BAR_HEIGHT)
#define BAR_SECTIONS_X_MARGIN      floor(BAR_SECTIONS_LENGTH/2)
#define BAR_SECTIONS_Y_MARGIN      round(DISPLAY_HEIGHT * 0.06)
#define BAR_SECTIONS_Y             (BAR_Y - BAR_SECTIONS_Y_MARGIN)
#define FIRST_SECTION_START_X      (FIRST_SECTION_X - BAR_SECTIONS_X_MARGIN)
#define SECOND_SECTION_START_X     (SECOND_SECTION_X - BAR_SECTIONS_X_MARGIN)
#define BAR_SECTIONS_STRIPE_DISTANCE 5

#define GRAPH_HEIGHT               round(DISPLAY_HEIGHT * 0.5)
#define GRAPH_START_Y              (GRAPH_END_Y + GRAPH_HEIGHT)
#define GRAPH_END_Y                (STATUS_MARGIN_TOP + STATUS_HEIGHT + STATUS_MARGIN_BOTTOM)
#define FIRST_SECTION_Y            map(LIMIT_GOOD, DISPLAYED_PPM_LOWEST, DISPLAYED_PPM_HIGHEST, GRAPH_START_Y, GRAPH_END_Y) //GRAPH_START_Y - map(LIMIT_GOOD, DISPLAYED_PPM_LOWEST, DISPLAYED_PPM_HIGHEST, 0, GRAPH_HEIGHT)
#define SECOND_SECTION_Y           map(LIMIT_MEDIUM, DISPLAYED_PPM_LOWEST, DISPLAYED_PPM_HIGHEST, GRAPH_START_Y, GRAPH_END_Y)
#define GRAPH_SECTIONS_STRIPE_DISTANCE 5

//SHORTS

//general
#define ROT ROTATION
#define DBR DISPLAY_BRIGHTNESS
#define LST LOADING_SCREEN_TIME
//display
#define DL  DISPLAY_LENGTH
#define DW  DISPLAY_HEIGHT
#define DHM DISPLAY_MARGIN_HORIZONTAL
#define DVM DISPLAY_MARGIN_VERTICAL
#define DLM DISPLAY_MARGIN_LEFT
#define DRM DISPLAY_MARGIN_RIGHT
#define DTM DISPLAY_MARGIN_TOP
#define DBM DISPLAY_MARGIN_BOTTOM
//font
#define LH  LETTER_HEIGHT
#define LW  LETTER_LENGTH
//Status Info
#define SH  STATUS_HEIGHT
#define SW  STATUS_LENGTH
#define STM STATUS_MARGIN_TOP
#define SS  STATUS_SIZE
//PPM
#define PLM PPM_MARGIN_LEFT
#define PBM PPM_MARGIN_BOTTOM
#define PRM PPM_MARGIN_RIGHT
#define PH  PPM_HEIGHT
#define PW  PPM_LENGTH
#define PY  PPM_Y
#define PS  PPM_SIZE
#define PSX PPM_STRING_X
#define PSS PPM_STRING_SIZE


//MACROS
#define SIZE(width, height, letters) (                        \
  (width <= 0 && height <= 0 || height <= 0 && letters <= 0) ? 1 :           \
  (width <= 0) ?  GETSIZE(DISPLAY_LENGTH, height, 1) :  \
  (height <= 0) ? GETSIZE(width, DISPLAY_HEIGHT, letters) :   \
                  GETSIZE(width, height, letters))

#define GETSIZE(width, height, letters) max((int) min(floor(height / LETTER_HEIGHT), floor(width / (LETTER_LENGTH*letters - 1))), 1)


//loadingScreen
#define LOADING_SCREEN_TITLE_SIZE 12
#define LOADING_SCREEN_SUB_SIZE 8
#define LOADING_SCREEN_DOTS_COLOR WHITE
#define LOADING_SCREEN_DOT_SIZE 10
