// Default color definitions
#define BLACK       0x0000      /*   0,   0,   0 */
#define NAVY        0x000F      /*   0,   0, 128 */
#define DARKGREEN   0x03E0      /*   0, 128,   0 */
#define DARKCYAN    0x03EF      /*   0, 128, 128 */
#define MAROON      0x7800      /* 128,   0,   0 */
#define PURPLE      0x780F      /* 128,   0, 128 */
#define OLIVE       0x7BE0      /* 128, 128,   0 */
#define LIGHTGREY   0xD69A      /* 211, 211, 211 */
#define DARKGREY    0x7BEF      /* 128, 128, 128 */
#define BLUE        0x001F      /*   0,   0, 255 */
#define GREEN       0x07E0      /*   0, 255,   0 */
#define DARKGREEN  0x03E0
#define CYAN        0x07FF      /*   0, 255, 255 */
#define RED         0xF800      /* 255,   0,   0 */
#define DARKRED     0x7800
#define MAGENTA     0xF81F      /* 255,   0, 255 */
#define YELLOW      0xFFE0      /* 255, 255,   0 */
#define WHITE       0xFFFF      /* 255, 255, 255 */
#define ORANGE      0xFDA0      /* 255, 180,   0 */
#define DARKORANGE 0xE3C0
#define GREENYELLOW 0xB7E0      /* 180, 255,   0 */
#define PINK        0xFE19      /* 255, 192, 203 */ //Lighter pink, was 0xFC9F
#define BROWN       0x9A60      /* 150,  75,   0 */
#define GOLD        0xFEA0      /* 255, 215,   0 */
#define SILVER      0xC618      /* 192, 192, 192 */
#define SKYBLUE     0x867D      /* 135, 206, 235 */
#define VIOLET      0x915C      /* 180,  46, 226 */
#define GREY        0x8C51
#define LIME        0x27F3
#define LIGHT_BLUE  0x4D9F
#define TURKISE     0x07FC



#define BLACK_MODE true

#define GRAPH_COLOR (BLACK_MODE) ? GRAPH_COLOR_BLACK : GRAPH_COLOR_LIGHT //WHITE//MAGENTA
#define BACKGROUND_COLOR (BLACK_MODE) ? BACKGROUND_COLOR_BLACK : BACKGROUND_COLOR_LIGHT
#define DATABOX_BACKGROUND_COLOR (BLACK_MODE) ? 0x2104 : WHITE//Fast schwarz
#define TIME_COLOR_CRITICAL  (BLACK_MODE) ? TIME_COLOR_CRITICAL_BLACK : TIME_COLOR_CRITICAL_LIGHT
#define TIME_COLOR_NORMAL  (BLACK_MODE) ? TIME_COLOR_NORMAL_BLACK : TIME_COLOR_NORMAL_LIGHT//WHITE
#define PPM_COLOR_N  (BLACK_MODE) ? PPM_COLOR_N_BLACK : PPM_COLOR_N_LIGHT //Normal
#define PPM_COLOR_R  (BLACK_MODE) ? PPM_COLOR_R_BLACK : PPM_COLOR_R_LIGHT//0xFE60 //Risk
#define PPM_COLOR_W  (BLACK_MODE) ? PPM_COLOR_W_BLACK : PPM_COLOR_W_LIGHT //Warning
#define PPM_COLOR_A  (BLACK_MODE) ? PPM_COLOR_A_BLACK : PPM_COLOR_A_LIGHT//MAROON//0xFA27 //Alarm
#define BAR_COLOR (BLACK_MODE) ? BAR_COLOR_BLACK : BAR_COLOR_LIGHT// WHITE
#define BAR_SECTIONS_COLOR  (BLACK_MODE) ? BAR_SECTIONS_COLOR_BLACK : BAR_SECTIONS_COLOR_LIGHT // WHITE
#define DATABOX_BAR_COLOR  (BLACK_MODE) ? DATABOX_BAR_COLOR_BLACK : DATABOX_BAR_COLOR_LIGHT //WHITE
#define DEFAULT_COLOR  (BLACK_MODE) ? DEFAULT_COLOR_BLACK : DEFAULT_COLOR_LIGHT //WHITE
#define CHART_BORDER_COLOR  (BLACK_MODE) ? CHART_BORDER_COLOR_BLACK : CHART_BORDER_COLOR_LIGHT
#define TEXT_COLOR (BLACK_MODE) ? TEXT_COLOR_BLACK : TEXT_COLOR_LIGHT
#define CHART_BACKGROUND_COLOR  (BLACK_MODE) ? CHART_BACKGROUND_COLOR_BLACK : CHART_BACKGROUND_COLOR_LIGHT


/*==============================================================================*/
#define GRAPH_COLOR_LIGHT BLACK //WHITE//MAGENTA
#define GRAPH_COLOR_BLACK WHITE //WHITE//MAGENTA

#define BACKGROUND_COLOR_LIGHT GREY
#define BACKGROUND_COLOR_BLACK BLACK

#define TEXT_COLOR_LIGHT BLACK
#define TEXT_COLOR_BLACK WHITE

#define TIME_COLOR_CRITICAL_LIGHT RED
#define TIME_COLOR_CRITICAL_BLACK RED

#define TIME_COLOR_NORMAL_LIGHT TEXT_COLOR//WHITE
#define TIME_COLOR_NORMAL_BLACK TEXT_COLOR//WHITE

#define PPM_COLOR_N_LIGHT GREEN //Normal
#define PPM_COLOR_N_BLACK GREEN //Normal

#define PPM_COLOR_R_LIGHT ORANGE//0xFE60 //Risk
#define PPM_COLOR_R_BLACK ORANGE//0xFE60 //Risk

#define PPM_COLOR_W_LIGHT RED //Warning
#define PPM_COLOR_W_BLACK RED //Warning

#define PPM_COLOR_A_LIGHT RED//MAROON//0xFA27 //Alarm
#define PPM_COLOR_A_BLACK RED//MAROON//0xFA27 //Alarm

#define BAR_COLOR_LIGHT TEXT_COLOR// WHITE
#define BAR_COLOR_BLACK TEXT_COLOR// WHITE

#define BAR_SECTIONS_COLOR_LIGHT TEXT_COLOR // WHITE
#define BAR_SECTIONS_COLOR_BLACK TEXT_COLOR // WHITE

#define DATABOX_BAR_COLOR_LIGHT GREY //WHITE
#define DATABOX_BAR_COLOR_BLACK TEXT_COLOR //WHITE

#define DEFAULT_COLOR_LIGHT TEXT_COLOR //WHITE
#define DEFAULT_COLOR_BLACK TEXT_COLOR //WHITE

#define CHART_BORDER_COLOR_LIGHT TEXT_COLOR
#define CHART_BORDER_COLOR_BLACK TEXT_COLOR

#define TEXT_COLOR_LIGHT BLACK
#define TEXT_COLOR_BLACK WHITE

#define CHART_BACKGROUND_COLOR_LIGHT GREY
#define CHART_BACKGROUND_COLOR_BLACK GREY
/*==============================================================================*/
